sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs

env:
  global:
  - SVN_REPO: https://plugins.svn.wordpress.org/hamelp/
  - secure: "mawPJiYPY1TMTBGEQyBF8ZBNe4QHyAHo0e5WudU6KQPXqz9ZSKPuAJJff3c3pmUz0ggBXN+MMxt0c2M+YMG5uVStohhVb40IC2hLEyqwR0n0bbg2NvQ/SpiE9tBDn+I0xfP35gZSDqDQXza1FWXXb2QxqlfMg6oB0MTFf4eka/OvJ2VHekO6HRkejzVWJCQ1eW7tCBA16ZnLsrZ7KOt/WstUufDpBjQsaJBGNME11Zb7La20uy/fOCdk32ULC3YBDWWydkLM1zvW6kYYZnYFF8jRbZEtpy+LjveuUiROtlhCBkBA5InsDxAlXpmGRnsWw7ql3pYlc+tJrH8dMDvGs2FDS4Ii+t4fbHbbcTdEOT6JIoW2c3vHVvR6+RGrIC5oAMaU6DRm+MUCSEqozbHUkqGg/BxlSncJpyE0iQzhAjl9mzq6UbHBGGE6h3QE72WatLHg5B5q/ylUFrRlC5XmZLq3Ixjb0YuQiHxhoHxgVrPL7xmdsk0gT2tNBdE60EZAUN2vjLWhs0PT9awmhXN4qayy3FLeLbPn2tWBjScJY9cg037tAeDc54Pw7FxrdsReFUJZ6yLeK6yC5c5AC3wyVRDTC1CJtJdxRsbfC7FklfUli8sdkiHCfGyILTqbUaW2EFbolmbSztFymGQU/2X7Wt6hD591P81iDbKPgWP1n5U="

before_script:
- composer install
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install v6.11.0
- node --version
- npm install && npm start
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
