<?php

namespace Hametuha\Hamelp\Hooks;


use Hametuha\Hamelp\Pattern\Singleton;

class PostParent extends Singleton {
	
	/**
	 * Add post meta box for post parent.
	 */
	protected function init() {
		
		
		
		parent::init(); // TODO: Change the autogenerated stub
	}
	
	
}
